volumes:
    test-backend-data:
    test-db-data:

networks:
    private:

services:
    test_db:
        image: postgres:17
        environment:
            POSTGRES_DB: kcidb_test
            POSTGRES_USER: test_user
            POSTGRES_PASSWORD: test_password
        volumes:
            - test-db-data:/var/lib/postgresql/data
            - ./backend/scripts/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
        networks:
            - private
        ports:
            - "5435:5432"

    redis:
        image: redis:8.0-M04-alpine
        restart: always
        networks:
            - private
        ports:
            - "6379:6379"

    test_backend:
        build:
            context: ./backend
            args:
                BACKEND_VOLUME_DIR: /volume_data
                INSTALL_DEV_DEPS: "true"
        volumes:
            - test-backend-data:/volume_data
        container_name: test_backend_service
        networks:
            - private
        ports:
            - target: 8000
              published: 8001
              protocol: tcp
              mode: host
        depends_on:
            - test_db
            - redis
        environment:
            DB_DEFAULT_NAME: kcidb_test
            DB_DEFAULT_USER: test_user
            DB_DEFAULT_PASSWORD: test_password
            DB_DEFAULT_HOST: test_db
            DB_DEFAULT_PORT: 5432
            DASH_DB_NAME: dashboard_test
            DASH_DB_USER: test_user
            DASH_DB_PASSWORD: test_password
            DASH_DB_HOST: test_db
            DASH_DB_PORT: 5432
            USE_DASHBOARD_DB: true
            DEBUG: false
            DEBUG_SQL_QUERY: false
            REDIS_HOST: redis
            CACHE_TIMEOUT: 60
            CORS_ALLOW_ALL_ORIGINS: true
